USE MASTER
GO

IF EXISTS (SELECT * FROM sys.databases WHERE NAME = 'StandardBook')
DROP DATABASE StandardBook
GO

CREATE DATABASE StandardBook
GO

USE StandardBook
GO

CREATE TABLE BOOK_TITLE(
	ISBN_Number int NOT NULL PRIMARY KEY IDENTITY(1,1),
	Title NVARCHAR(20) NOT NULL,
	PublisherID INT NOT NULL,
	PublishedDate DATETIME NOT NULL,
	BookFormat INT NOT NULL,
	Pages INT NOT NULL,
	Price Decimal(19,4) NOT NULL,
	)
GO 
CREATE TABLE AUTHOR(
	AuthorID INT PRIMARY KEY IDENTITY(1,1),
	AuthorFirstName NVARCHAR(20) NOT NULL,
	AuthorLastName NVARCHAr(20) NOT NULL,
	)
GO
CREATE TABLE BOOK_AUTHOR(
	ISBN_Number INT,
	AuthorID INT,
	PRIMARY KEY(ISBN_Number,AuthorID),
	CONSTRAINT FK_BOOK_AUTHOR_BOOK_TITLE FOREIGN KEY(ISBN_Number) REFERENCES BOOK_TITLE(ISBN_Number),
	CONSTRAINT FK_BOOK_AUTHOR_AUTHOR FOREIGN KEY(AuthorID) REFERENCES AUTHOR(AuthorID)
	)
GO
CREATE TABLE PUBLISHER(
	PublisherID INT PRIMARY KEY IDENTITY(1,1),
	PublisheName NVARCHAR(20) NOT NULL,
	)
GO
CREATE TABLE CATEGORY(
	CategoryID INT PRIMARY KEY IDENTITY(1,1),
	CategoryDescription NVARCHAR(20) NOT NULL,
	)
GO
CREATE TABLE BOOK_CATEGORY(
	ISBN_Number INT,
	CategoryID INT,
	PRIMARY KEY(ISBN_Number,CategoryID),
	CONSTRAINT FK_BOOK_CATEGORY_BOOK_TITLE FOREIGN KEY(ISBN_Number) REFERENCES BOOK_TITLE(ISBN_Number),
	CONSTRAINT FK_BOOK_CATEGORY_CATEGORY FOREIGN KEY(CategoryID) REFERENCES CATEGORY(CategoryID)
	)
GO
CREATE TABLE BOOK_FORMAT(
	BookFormat INT PRIMARY KEY IDENTITY(1,1),
	FormatDescription NVARCHAR(20) NOT NULL,
	)
GO
ALTER TABLE BOOK_TITLE ADD CONSTRAINT FK_BOOK_TITLE_PUBLISHER FOREIGN KEY (PublisherID) REFERENCES PUBLISHER(PublisherID)
GO
ALTER TABLE BOOK_TITLE ADD CONSTRAINT FK_BOOK_TITLE_BOOK_FORMAT FOREIGN KEY (BookFormat) REFERENCES BOOK_FORMAT(BookFormat)
GO